# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Using R for Data Analysis and Visualization
description:      
url:              https://axelanne.github.io/UsingR/
baseurl:          /Using R
email:            axel@marshall.edu
feedbackurl:      
author:
  name:           'Ethan White'
  url:            https://twitter.com/ethanwhite

github:
  repo:           https://github.com/axelanne/UsingR.git
  #               Be sure the 'Issues' feature is activated in 'Settings'
